### ISSUE TITLE
feat: support openai key

### ISSUE THREAD

**Issue by ObservedObserver** [ObservedObserver/viz-gpt#3]
This repo is now using azure services. Add support for openai services in future.

**Comment by fchange** [comment]
催更

**Comment by louis-sanna-dev** [comment]
@ObservedObserver done https://github.com/ObservedObserver/viz-gpt/pull/9/files

**Comment by ObservedObserver** [comment]
> @ObservedObserver done https://github.com/ObservedObserver/viz-gpt/pull/9/files

Thanks!!
