### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by logust79** [ObservedObserver/viz-gpt#5]
First of all, this project looks amazing! Thanks for all the good work.

However, I have this error when trying to visualise an example chart. When I pull up the console, I see this:
`POST http://localhost:5173/api/vizchat 404 (Not Found)`
Perhaps I have to run `vizchat` as a server in a separate instance?

**Comment by ObservedObserver** [comment]
Try ‘vercel dev’, which runs both the api and front-end together.

**Comment by logust79** [comment]
That works. Thank you!

**Comment by tm7bhyh79m** [comment]
After a few try and error, the `vercel dev` is working. But I still get a different version of JSON error when click visualize.

`Unexpected token 'F', "FetchError"... is not valid JSON`

If I use `npm run dev`, I will get `Unexpected end of JSON input` or `JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`.

This is really a great project. But I don't seems to have enough ability to selfhost it at this stage.

Would you mind give me a little bit more guide of how to solve these JSON errors?
And are you considering provide an official dockerfile like Rath project do?
