### ISSUE TITLE
plot heatmap not work well

### ISSUE THREAD

**Issue by Liripo** [ObservedObserver/viz-gpt#6]
![image](https://github.com/ObservedObserver/viz-gpt/assets/54770415/89e8c128-d096-4fcc-9984-3214beb5dc71)
My data is:
![image](https://github.com/ObservedObserver/viz-gpt/assets/54770415/b01e74de-072b-4909-b7e4-091a3d9f07fd)

**Comment by ObservedObserver** [comment]
This is not tabular data for the heatmap. I understand you want to make a heatmap based on a matrix, but you need to transform the matrix into tabular data first.

example:
```
from,to,value
mpg,mpg,1
mpg,cyl,-0.852
...
```

Then you can draw this heatmap where x-axis is from and y-axis is to and color is value.

**Comment by Liripo** [comment]
Thank you,I see.
